### ISSUE TITLE
Beginner's Confusion

### ISSUE THREAD

**Issue by mike-dev** [nelsonpecora/quiz-text#8]
I'm attempting to use this package but I'm at a complete loss as to how it's installed. I have a project using npm and ZURB foundation. I'm not sure if I need to create a gulp task, a helper (handlebars) file or attempt to directly call the package. I've completed the npm install but just not sure what to do next in order to implement. Any insight would be greatly appreciated. Thank you

**Comment by nelsonpecora** [comment]
Hi! I just realized I forgot to add a pretty key bit of the documentation (namely, how to use it once it's installed). Here are the steps:

1. install via npm (`npm install --save quiz-text`)
2. use server-side by requiring the parser (`var parse = require('quiz-text').parse`)
3. pass a string of markdown into the parser to get the generated JSON output (`var output = parse(' some markdown ')`

I'm going to update the readme to include this (kinda necessary 😅 ) info, but that should work. Right now quiz-text is only _officially_ supported in node, but I think it should work in the browser (compiled via browserify, webpack, rollup, etc). I'm going to run some tests to verify it works in the browser over the next week or so.

Until then, [here's](http://dontkry.com/posts/code/using-npm-on-the-client-side.html) a pretty decent tutorial on getting npm modules to work via browserify, and [here's](https://webpack.js.org/guides/get-started/) a webpack one (if you replace `lodash` with `quiz-text`)

Please let me or @alliesahn know if you have any questions!

**Comment by mike-dev** [comment]
Excellent and thanks for the response & I will give it a shot!

**Comment by nelsonpecora** [comment]
Thanks! I'm gonna close this issue, but feel free to reopen if you have additional questions.
